// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udtkdtetfjxyiewomzht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdGtkdGV0Zmp4eWlld29temh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDQ5NzAsImV4cCI6MjA2MDgyMDk3MH0.gix23LdqrvwHlwI95E-OMNKLk_SL08e9V-sli6xuDPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);